name: nido
favicon: null
layout_spectrum: 0.66828339593485
typography_spectrum: 0.45196035876870155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6700153760612011
  lightness: 0.2813840825110674
  saturation: 0.6986577045172453
  rhythmicContrast: 0.5861851961817592
purpose: []
